name: Actividad Ingesta y Limpieza de Datos

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout repo
        uses: actions/checkout@v4

      # Paso 2: Configuración de Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'

      # Paso 3: Crear entorno virtual
      - name: Crear entorno virtual
        run: python -m venv venv

      # Paso 4: Activar entorno virtual
      - name: Activar entorno virtual
        run: .\venv\Scripts\activate

      # Paso 5: Instalar dependencias desde requirements.txt
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 6: Ejecutar el script de ingesta de datos
      - name: Ejecutar ingestion.py
        run: python src/ingestion.py

      # Paso 7: Ejecutar el script de limpieza de datos
      - name: Ejecutar cleaning.py
        run: python src/cleaning.py

      # Paso 8: Commit y Push de los cambios generados
      - name: Commit y Push cambios
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Generación automática de archivos de ingestión y limpieza'
          commit_user_name: 'GitHub Actions'
          commit_user_email: 'actions@github.com'

      # Paso 9: Subir los archivos generados (CSV y reporte de auditoría)
      - name: Subir archivos limpios y reporte de auditoría
        uses: actions/upload-artifact@v4
        with:
          name: cleaned-data
          path: |
            src/static/xlsx/cleaned_data.csv
            src/static/auditoria/cleaning_report.txt
