name: Actividad Ingesta y Limpieza de Datos

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'

      # Step 3: Create virtual environment
      - name: Create virtual environment
        run: python -m venv venv

      # Step 4: Activate virtual environment
      - name: Activate virtual environment
        run: .\venv\Scripts\activate

      # Step 5: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 6: Run ingestion script
      - name: Run ingestion.py
        run: python src/ingestion.py

      # Step 7: Run cleaning script
      - name: Run cleaning.py
        run: python src/cleaning.py

      # Step 8: Run enrichment pipeline
      - name: Run enrichment.py
        run: python src/enrichment.py

      # Step 9: Commit and push generated files (optional)
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Auto-generated data files and reports'
          commit_user_name: 'GitHub Actions'
          commit_user_email: 'actions@github.com'

      # Step 10: Upload cleaned & enriched data and reports
      - name: Upload cleaned & enriched data and reports
        uses: actions/upload-artifact@v4
        with:
          name: enriched-artifacts
          path: |
            src/static/xlsx/cleaned_data.csv
            src/static/auditoria/cleaning_report.txt
            data/enriched_data.csv
            data/enrichment_report.txt
