name: Actividad Ingesta y Limpieza de Datos

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'

      - name: Crear entorno virtual
        run: python -m venv venv

      - name: Activar entorno virtual
        run: .\venv\Scripts\activate

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script ingestion.py
        run: python src/ingestion.py

      - name: Ejecutar script cleaning.py
        run: python src/cleaning.py

      - name: Mostrar primeros registros del CSV limpio
        run: |
          echo "Primeros registros de cleaned_data.csv:"
          head -n 10 src/static/xlsx/cleaned_data.csv

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Generación automática de archivos de ingestión y limpieza'
          commit_user_name: 'Carlos Cardona [GitHub Actions]'
          commit_user_email: 'carlos.cardona@est.iudigital.edu.co'
          commit_author: 'Carlos Cardona <carlos.cardona@est.iudigital.edu.co>'

      - name: Upload cleaned data and audit report
        uses: actions/upload-artifact@v4
        with:
          name: cleaned-data
          path: |
            src/static/xlsx/cleaned_data.csv
            src/static/auditoria/cleaning_report.txt